<?php
/***************************************************************
 * Extension Manager/Repository config file for ext: "jn_phpcontentelement"
 *
 * Auto generated by Extension Builder 2017-09-12
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => '[joppnet] PHP Content Element',
    'description' => 'Allows you to add PHP scripts via frontend plugin.',
    'category' => 'plugin',
    'author' => 'Oliver Schlöbe',
    'author_email' => 'oli@joppnet.de',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 1,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.0.0-8.7.99'
        ],
        'conflicts' => [],
        'suggests' => [
        	't3editor' => '8.0.0-0.0.0'
        ],
    ],
];
